server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:IlianMetina/healthcare-config.git
          uri: https://github.com/IlianMetina/healthcare-config.git
          default-label: master
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
#          Changer URI vers lien repo github HTTPS/SSH