spring:
  application:
    name: user
  config:
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: +APy/jgm0ouuw1/WSoUTvsjcTsysxO3GmaFljb++w8=
  expiration: 86400000